[package]
name = "guessbusters"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = "1.0.228"
serde_json = "1.0.145"
serde_derive = "1.0.228"
rand = "0.9.2"
